---
title: "phd symposium figures"
author: "Dan Ovando"
date: "2/9/2018"
output: html_document
---

```{r}

library(gbm)
library(randomForest)
library(stringr)
library(modelr)
library(broom)
library(hrbrthemes)
library(viridis)
library(sf)
library(ggmap)
library(caret)
library(extrafont)
library(gganimate)
library(patchwork)
library(tidyverse)
demons::load_functions("../functions")

run_name <- 'testing-gfw_only'

run_dir <- here::here('results',run_name)

fig_theme <- theme_ipsum(base_size = 12, axis_title_size = 14,subtitle_size = 10, axis_text_size = 12, plot_title_size = 10) + 
  theme(plot.margin = unit(c(.25,.25,.25,.25), "in"))

theme_set(fig_theme)

load(here::here("results", run_name,'skynet_data.Rdata'))

load(here::here("results", run_name,'processed_skynet_models.Rdata'))

load(here::here("results", run_name,'vast_fish.Rdata'))

load(file = here::here("data","global_map.Rdata"))

load(file = here::here('data','fish_prices.Rdata'))

load(file = here::here('results',run_name,'gfw_data.Rdata'))

width <- 5.25

height <- width / 1.8

map_size <- 1
```

# We Need some Models


```{r}



naive_trends <- skynet_data %>%
  group_by(rounded_lat, rounded_lon, year) %>%
  summarise(total_abundance = sum(biomass),
            total_engine_hours = sum(total_engine_hours),
            survey = unique(survey)[1]) %>% 
  filter(total_engine_hours > 0) %>% 
  ungroup()

naive_plot <- naive_trends %>% 
  ggplot(aes(log(total_engine_hours), log(total_abundance))) + 
  geom_point(shape = 21, size = 3, alpha = 0.5, fill = "steelblue") + 
geom_smooth(method = "lm") + 
  labs(x = "Log(Fishing)", y = "Log(Fish)")


  ggsave(file = "naive_plot.png", naive_plot, height = height, width = width, units = c("in"),
         device = "png")

```


# Survey Data Provides "True" Estimates

```{r}



knots <- vast_fish %>%
  select(survey, vasterized_data) %>%
  mutate(knots = map(vasterized_data, c('spatial_list', 'loc_x_lat_long'))) %>%
  select(-vasterized_data) %>%
  unnest() %>%
  mutate(recenter_lon = ifelse(approx_long < 0, 180 + (180 - abs(approx_long)), approx_long))
  
  pacific_map <- global_map %>%
  as("Spatial") %>%
  maptools::nowrapRecenter() %>%
  sf::st_as_sf()
  
  
  map_knots <-  knots %>%
  dplyr::mutate(geometry = purrr::map2(recenter_lon, approx_lat, ~ sf::st_point(x = c(.x, .y), dim = 'XY'))) %>%
  ungroup() %>%
  mutate(geometry = sf::st_sfc(geometry, crs =
  "+proj=longlat +datum=WGS84 +no_defs")) %>%
  sf::st_sf()
  
  test <- st_make_grid(map_knots, cellsize = 2, what = "centers") %>% 
    sf::st_sf()
  
  
  bbox <- sf::st_bbox(map_knots)
  
 survey_names <- tribble(
  ~ survey,
  ~ name,
  'ebsbts',
  'Eastern Bering Sea',
  'aibts',
  'Aleutian Islands',
  'goabts',
  'Gulf of Alaska',
  'wcgbts',
  'West Coast',
  'wcghl',
  "SB Channel"
)
  
  knot_map <- map_knots %>%
    left_join(survey_names, by = "survey") %>% 
  ggplot() +
  geom_sf(aes(color = name), size = 1, alpha = 0.5, show.legend = F) +
  geom_sf(data = pacific_map, fill = 'grey60') +
  coord_sf(xlim = c(bbox['xmin'], bbox['xmax']),
  ylim = c(bbox['ymin'], bbox['ymax'])) +
  theme_light(base_size = 12) +
  scale_color_viridis_d(name = element_blank())
  

  ggsave(file = "knot_map.png", knot_map, height = height, width = width)

```

# We can link to GFW Surveys


```{r}

naive_trends <- skynet_data %>%
  group_by(rounded_lat, rounded_lon, year) %>%
  summarise(total_abundance = sum(density),
            total_engine_hours = sum(total_engine_hours),
            survey = unique(survey)[1]) %>%
  ungroup() %>%
    mutate(total_abundance = pmin(2,(total_abundance - mean(total_abundance)) / (sd(total_abundance))),
         total_engine_hours =pmin(2,(total_engine_hours - mean(total_engine_hours)) / (sd(total_engine_hours)))) %>% 
  # mutate(total_abundance = total_abundance / max(total_abundance),
  #        total_engine_hours = total_engine_hours / max(total_engine_hours)) %>% 
  mutate(recenter_lon = ifelse(rounded_lon < 0, 180 + (180 - abs(rounded_lon)), rounded_lon)) 



ebs_fishing <-  naive_trends %>%
  filter(survey == "ebsbts") %>% 
  dplyr::mutate(geometry = purrr::map2(recenter_lon, rounded_lat, ~ sf::st_point(x = c(.x, .y), dim = 'XY'))) %>%
  ungroup() %>%
  mutate(geometry = sf::st_sfc(geometry, crs =
                                 "+proj=longlat +datum=WGS84 +no_defs")) %>%
  sf::st_sf()

years <- expand.grid(id = 1:nrow(pacific_map), year = unique(ebs_fishing$year))

yearly_map <- pacific_map %>% 
  mutate(id = 1:nrow(.)) %>% 
  right_join(years, by = "id")
  
bbox <- sf::st_bbox(ebs_fishing)

naive_fishing_map <- ebs_fishing %>%
  ggplot(aes(frame = year)) +
  geom_raster(aes(x = recenter_lon, y = rounded_lat, fill = (total_engine_hours)), show.legend = F) +
    geom_sf(data = yearly_map, fill = 'grey60') +
  coord_sf(xlim = c(bbox['xmin'], bbox['xmax']),
           ylim = c(bbox['ymin'], bbox['ymax'])) +
  scale_fill_viridis_c(name = "Fishing") +
  labs(x = "Longitude", y = "Latitude", 
       subtitle = "Fishing Pressure")

gganimate(naive_fishing_map, "ebsbts-fishing-map.gif", width = width, height = height)


naive_fish_map <- ebs_fishing %>%
  ggplot(aes(frame = year)) +
  geom_raster(aes(x = recenter_lon, y = rounded_lat, fill = (total_abundance)), show.legend = F) +
  geom_sf(data = yearly_map, fill = 'grey60') +
  # geom_sf(aes(color = survey), size = 1, alpha = 0.5) +
  coord_sf(xlim = c(bbox['xmin'], bbox['xmax']),
           ylim = c(bbox['ymin'], bbox['ymax'])) +
    # scale_fill_gradientn(colours = RColorBrewer::brewer.pal(9,"Reds"), name = "Fishing") +
  # scale_fill_gradient(low = "steelblue", high = "tomato", name = "Fish") +
    scale_fill_viridis_c(name = "Fish") +
  labs(x = "Longitude", y = "Latitude", 
       subtitle = "Fish Abundance")

gganimate(naive_fish_map, "ebsbts-fish-map.gif", width = width, height = height)


```

# Machine Learning Works Better


```{r}

skynet_models$data_subset[str_detect(skynet_models$data_subset,"uncentered")] <- "skynet"

coast_wide <- skynet_models %>% 
  filter(model %in% c('ranger','structural'), test_set == 'random', train_set == 'random',
                      data_subset == "skynet") %>% 
  select(dep_var, model,test_data, psuedo_r2 ) %>% 
  unnest()


r2 <- coast_wide %>% 
  filter(dep_var == "log_density") %>% 
  select(model, psuedo_r2) %>% 
  group_by(model) %>% 
  summarise(r2 = pmax(0,unique(psuedo_r2)))

translate_model <- c(
  ranger = glue::glue("Machine Learning: R2 = {r2$r2[1]}"),
  structural = glue::glue("Bioeconomic: R2 = {r2$r2[2]}")
)

coast_wide_performance <- coast_wide %>% 
  filter(dep_var == "log_density") %>% 
  ggplot(aes(log_density, pred)) + 
  geom_abline(aes(slope = 1, intercept = 0), linetype = 2, color = "red") +
  geom_point(color = "steelblue", alpha = 0.5, size = 1.5) + 
  geom_smooth(method = "lm", se = F) +
  facet_wrap( ~ model, scales = "free_y", labeller = labeller(model = translate_model)) + 
  labs(x = "Observed", y = "Predicted") + 
  theme(strip.text = element_text(size = 12))

psuedo_r2 <- coast_wide %>% 
  filter(dep_var == "log_density") %>% 
  group_by(model) %>% 
  summarise(r2 = pmax(0,unique(psuedo_r2))) %>% 
  ggplot(aes(model, r2)) + 
  geom_col() + 
  geom_hline(aes(yintercept = 0)) + 
  theme_classic() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 16),
        axis.text.y = element_text(size = 16)) + 
  labs(y = expression(R^2))

combo <- coast_wide_performance + psuedo_r2 + plot_layout(ncol = 1, nrow = 2, heights = c(2,1))


  ggsave(file = "coast_wide_performance.png", coast_wide_performance, height = height, width = width)


```

# the past can predict the future

```{r}

predict_future <- skynet_models %>% 
  filter(model %in% c('ranger'), test_set == 'year_gr_than_2014', train_set == 'year_leq_than_2014',
                      data_subset == "skynet", 
         dep_var == "log_density") %>% 
  select(dep_var, model,test_data, psuedo_r2 ) %>% 
  unnest()

future_performance <- predict_future %>% 
  ggplot(aes(log_density, pred)) + 
  geom_abline(aes(slope = 1, intercept = 0), linetype = 2, color = "red") +
  geom_point(aes(fill = factor(year)),shape = 21, alpha = 0.75, size = 2, show.legend = F) + 
  geom_smooth(method = "lm", se = F, alpha = 0.5) +
  labs(x = "Observed", y = "Predicted", 
       title = glue::glue("R2 is {unique(predict_future$psuedo_r2)}")) + 
  theme(strip.text = element_text(size = 10)) + 
  scale_fill_viridis_d(name = "Year", option = "D")

  ggsave(file = "future_performance.png", future_performance, height = height, width = width)

```

# Use Alaska to Predict West Coast

```{r}

predict_west_coast <- skynet_models %>% 
  filter(model %in% c('ranger'), test_set == 'west_coast', train_set == 'not_west_coast',
                      data_subset == "skynet", 
         dep_var == "log_density") %>% 
  select(dep_var, model,test_data, psuedo_r2 ) %>% 
  unnest()

westcoast_performance <- predict_west_coast %>% 
  ggplot(aes(log_density, pred)) + 
  geom_abline(aes(slope = 1, intercept = 0), linetype = 2, color = "red") +
  geom_point(aes(fill = survey),shape = 21, alpha = 0.75, size = 2) + 
  geom_smooth(method = "lm", se = F, alpha = 0.5) +
  labs(x = "Observed", y = "Predicted", 
       title = glue::glue("R2 is {pmax(0,unique(predict_west_coast$psuedo_r2))}")) + 
  scale_fill_viridis_d(name = "Survey", option = "D")

  ggsave(file = "westcoast_performance.png", westcoast_performance, height = height, width = width)

```


# spatial Residuals Map


```{r}


coast_wide <- skynet_models %>%
  filter(
  model %in% c('ranger'),
  test_set == 'random',
  train_set == 'random',
  data_subset == "skynet",
  dep_var == "log_density"
  ) %>%
  select(dep_var, model, test_data, psuedo_r2) %>%
  unnest()  %>%
  mutate(residuals = log_density - pred) %>%
  group_by(year, rounded_lat, rounded_lon) %>%
  summarise(
  total_error = sum(residuals) ^ 2,
  total_observed = sum(log_density),
  total_pred = mean(pred)
  ) %>%
  ungroup() %>%
  mutate(recenter_lon = ifelse(rounded_lon < 0, 180 + (180 - abs(rounded_lon)), rounded_lon))
  
  
  coast_map <-  coast_wide %>%
  dplyr::mutate(geometry = purrr::map2(recenter_lon, rounded_lat, ~ sf::st_point(x = c(.x, .y), dim = 'XY'))) %>%
  ungroup() %>%
  mutate(geometry = sf::st_sfc(geometry, crs =
  "+proj=longlat +datum=WGS84 +no_defs")) %>%
  sf::st_sf()
  
  
  bbox <- sf::st_bbox(coast_map)
  
  coastal_abundance <- coast_map %>%
  ggplot() +
  geom_raster(aes(recenter_lon, y = rounded_lat, fill = total_pred)) +
  geom_sf(data = pacific_map, fill = 'grey60') +
  # geom_sf(aes(color = total_pred), size = 1, alpha = 0.5) +
  coord_sf(xlim = c(bbox['xmin'], bbox['xmax']),
  ylim = c(bbox['ymin'], bbox['ymax'])) +
  theme_light(base_size = 10) +
  scale_fill_viridis(name = "Predicted Fish") +
  theme(legend.position = "top", axis.title = element_blank(),
        legend.key.width = unit(1.25,'cm'),
        legend.title = element_text(size = 8), 
        legend.margin = unit(c(0,0,0,0), "cm"))
  
  
  ggsave(file = "predicted_abundance_map.png",
         device = "png",
  coastal_abundance,
  height = height,
  width = width)
  
  
  coastal_error <- coast_map %>%
  ggplot() +
  geom_raster(aes(recenter_lon, y = rounded_lat, fill = total_error)) +
  geom_sf(data = pacific_map, fill = 'grey60') +
  # geom_sf(aes(color = total_pred), size = 1, alpha = 0.5) +
  coord_sf(xlim = c(bbox['xmin'], bbox['xmax']),
  ylim = c(bbox['ymin'], bbox['ymax'])) +
  theme_light(base_size = 18) +
  scale_fill_viridis(name = "Predicted Abundance",
                     guide = guide_colorbar(n = 100)) +
  theme(legend.position = "top", axis.title = element_blank(),
        legend.key.width = unit(1.25,'cm'),
        legend.title = element_text(size = 8), 
        legend.margin = unit(c(0,0,0,0), "cm"))  
  
  ggsave(file = "error_map.png",
  coastal_error,
  height = height,
  width = width)
  
  coastal_truth<- coast_map %>%
  ggplot() +
  geom_raster(aes(recenter_lon, y = rounded_lat, fill = total_observed)) +
    geom_sf(data = pacific_map, fill = 'grey60') +
  # geom_sf(aes(color = total_pred), size = 1, alpha = 0.5) +
  coord_sf(xlim = c(bbox['xmin'], bbox['xmax']),
  ylim = c(bbox['ymin'], bbox['ymax'])) +
  theme_light(base_size = 18) +
  scale_fill_viridis(name = "Observed Abundance") +
  theme(legend.position = "top", axis.title = element_blank(),
        legend.key.width = unit(1.25,'cm'),
        legend.title = element_text(size = 8), 
        legend.margin = unit(c(0,0,0,0), "cm"))
  
  
  ggsave(file = "observed_abundance_map.png",
  coastal_truth,
  height = height,
  width = width)
  

```

# naive model

```{r}

naive_plot <- skynet_data %>% 
  group_by(survey, year) %>% 
  summarise(total_abundance = log(sum(biomass, na.rm = T)),
            total_effort = log(sum(total_hours, na.rm = T))) %>% 
  ggplot(aes(total_effort, total_abundance, fill = survey)) + 
  geom_point(shape = 21, size = 2) + 
  scale_fill_viridis_d() 

  ggsave(file = "naive_model.png",
  naive_plot,
  height = height,
  width = width)
  
  naive_plot <- skynet_data %>% 
    filter(survey != "wcghl") %>% 
  group_by(survey, year) %>% 
  summarise(total_abundance = log(sum(biomass, na.rm = T)),
            total_effort = log(sum(total_hours, na.rm = T))) %>% 
  ggplot(aes(total_effort, total_abundance, fill = survey)) + 
  geom_point(shape = 21, size = 2) + 
  scale_fill_viridis_d() 

  ggsave(file = "naive_model.png",
  naive_plot,
  height = height,
  width = width)
  
  
```


# More naive model


```{r}

tester <- skynet_models %>% 
  filter(model %in% c('ranger'), test_set == 'random', train_set == 'random',
                      data_subset == "skynet", dep_var == "log_density") %>% {
                        .$test_data[[1]]
                      }

test_resolution <- data_frame(data = list(tester), resolution = seq(25,200, by = 25)) %>% 
  mutate(new_grid  = map2(data,  resolution, create_grid, lon_name = rounded_lon, lat_name = rounded_lat))

test_resolution <-  test_resolution %>% 
  mutate(new_data = map2(data, new_grid, snap_to_grid,
                         old_lon_name = rounded_lon,
                         old_lat_name = rounded_lat, 
                         new_lon_name = lon, 
                         new_lat_name = lat))


check <- test_resolution %>% 
  select(resolution, new_data) %>% 
  unnest()


check_plot <- check %>% 
  group_by(resolution) %>% 
  ggplot(aes(agg_mean_log_density, agg_pred, color = year, frame = resolution )) + 
  geom_point() + 
  geom_smooth(method = "lm") +
  scale_color_viridis() + 
  labs(subtitle = "km^2 resolution")

gganimate(check_plot, "resolution.gif")


```

# West Coast resolution plot

```{r}

tester <- skynet_models %>% 
  filter(model %in% c('ranger'), test_set == 'west_coast', train_set == 'not_west_coast',
                      data_subset == "skynet", dep_var == "log_density") %>% {
                        .$test_data[[1]]
                      }

test_resolution <- data_frame(data = list(tester), resolution = seq(25,200, by = 25)) %>% 
  mutate(new_grid  = map2(data,  resolution, create_grid, lon_name = rounded_lon, lat_name = rounded_lat))

test_resolution <-  test_resolution %>% 
  mutate(new_data = map2(data, new_grid, snap_to_grid,
                         old_lon_name = rounded_lon,
                         old_lat_name = rounded_lat, 
                         new_lon_name = lon, 
                         new_lat_name = lat))


check <- test_resolution %>% 
  select(resolution, new_data) %>% 
  unnest()


check_plot <- check %>% 
  group_by(resolution) %>% 
  ggplot(aes(agg_mean_log_density, agg_pred, color = year, frame = resolution )) + 
  geom_point() + 
  geom_smooth(method = "lm") +
  scale_color_viridis() + 
  labs(subtitle = "km^2 resolution")

gganimate(check_plot, "westcoast-resolution.gif")


```

# varimp

```{r}

final_model <- skynet_models %>% 
  filter(model %in% c('ranger'), test_set == 'random', train_set == 'random',
                      data_subset == "skynet", dep_var == "log_density") %>% {
                        .$results[[1]]$finalModel
                      }

var_imp <- final_model$variable.importance %>% 
  broom::tidy() %>% 
  rename(variable = names, importance = x) %>% 
  mutate(variable = fct_reorder(variable,importance))

var_imp_plot <- var_imp %>% 
  ggplot(aes(variable, importance)) + 
  geom_col() + 
  coord_flip()

  ggsave(file = "varimp.png",
  var_imp_plot,
  height = height,
  width = width)


```





